-- PRIORITAS 8 — Analytics sederhana
-- Jalankan sekali di Supabase SQL Editor.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.sites(id) on delete cascade,
  visitor_id text not null,
  event_type text not null check (event_type in ('open','location_click','gift_click','music_play','rsvp')),
  source text not null default 'direct',
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_site_created_idx on public.analytics_events(site_id,created_at desc);
create index if not exists analytics_events_site_type_idx on public.analytics_events(site_id,event_type,created_at desc);
create index if not exists analytics_events_site_visitor_idx on public.analytics_events(site_id,visitor_id);

alter table public.analytics_events enable row level security;
drop policy if exists "analytics_owner_read" on public.analytics_events;
create policy "analytics_owner_read" on public.analytics_events
for select to authenticated
using (exists(select 1 from public.sites s where s.id=analytics_events.site_id and s.owner_id=auth.uid()));

-- Public visitors never insert directly. This RPC validates publication status and rate-limits duplicates.
create or replace function public.track_analytics_event(
  p_site uuid,
  p_visitor text,
  p_event text,
  p_source text default 'direct',
  p_path text default '',
  p_meta jsonb default '{}'::jsonb
) returns void
language plpgsql security definer set search_path=public
as $$
begin
  if p_site is null or coalesce(length(trim(p_visitor)),0)<6 then return; end if;
  if p_event not in ('open','location_click','gift_click','music_play','rsvp') then return; end if;
  if not exists(select 1 from public.sites where id=p_site and status='published') then return; end if;
  -- Open: one session event per anonymous visitor every 30 minutes.
  if p_event='open' and exists(
    select 1 from public.analytics_events
    where site_id=p_site and visitor_id=left(p_visitor,100) and event_type='open'
      and created_at>now()-interval '30 minutes'
  ) then return; end if;
  -- Guard accidental double-clicks for interaction events.
  if p_event<>'open' and exists(
    select 1 from public.analytics_events
    where site_id=p_site and visitor_id=left(p_visitor,100) and event_type=p_event
      and created_at>now()-interval '2 seconds'
  ) then return; end if;
  insert into public.analytics_events(site_id,visitor_id,event_type,source,path,metadata)
  values(p_site,left(p_visitor,100),p_event,left(coalesce(nullif(trim(p_source),''),'direct'),80),left(coalesce(p_path,''),500),coalesce(p_meta,'{}'::jsonb));
end;
$$;

revoke all on function public.track_analytics_event(uuid,text,text,text,text,jsonb) from public;
grant execute on function public.track_analytics_event(uuid,text,text,text,text,jsonb) to anon, authenticated;

-- Owner-only dashboard summary. Missing calendar dates are filled with zero.
create or replace function public.analytics_summary(
  p_site uuid,
  p_from date default (current_date-29),
  p_to date default current_date
) returns jsonb
language plpgsql security definer set search_path=public
as $$
declare result jsonb;
begin
  if not exists(select 1 from public.sites where id=p_site and owner_id=auth.uid()) then
    raise exception 'not allowed' using errcode='42501';
  end if;
  if p_from is null then p_from:=current_date-29; end if;
  if p_to is null then p_to:=current_date; end if;
  if p_from>p_to then raise exception 'invalid date range'; end if;
  if p_to-p_from>366 then p_from:=p_to-366; end if;

  with filtered as (
    select * from public.analytics_events
    where site_id=p_site and created_at>=p_from::timestamptz and created_at<(p_to+1)::timestamptz
  ), days as (
    select d::date day from generate_series(p_from::timestamp,p_to::timestamp,interval '1 day') d
  ), daily as (
    select days.day,
      count(f.id) filter(where f.event_type='open')::int opens,
      count(distinct f.visitor_id)::int visitors,
      count(f.id) filter(where f.event_type='rsvp')::int rsvps
    from days left join filtered f on f.created_at>=days.day::timestamptz and f.created_at<(days.day+1)::timestamptz
    group by days.day order by days.day
  ), src as (
    select source,count(*) filter(where event_type='open')::int total
    from filtered group by source having count(*) filter(where event_type='open')>0 order by total desc,source limit 12
  ), totals as (
    select
      count(*) filter(where event_type='open')::int opens,
      count(distinct visitor_id) filter(where event_type='open')::int unique_visitors,
      count(*) filter(where event_type='location_click')::int location_clicks,
      count(*) filter(where event_type='gift_click')::int gift_clicks,
      count(*) filter(where event_type='music_play')::int music_plays,
      count(*) filter(where event_type='rsvp')::int rsvps
    from filtered
  )
  select jsonb_build_object(
    'from',p_from,'to',p_to,
    'totals',jsonb_build_object(
      'opens',t.opens,'uniqueVisitors',t.unique_visitors,'locationClicks',t.location_clicks,
      'giftClicks',t.gift_clicks,'musicPlays',t.music_plays,'rsvps',t.rsvps,
      'rsvpRate',case when t.opens>0 then round((t.rsvps::numeric/t.opens::numeric)*100,1) else 0 end
    ),
    'daily',(select coalesce(jsonb_agg(jsonb_build_object('date',day,'opens',opens,'visitors',visitors,'rsvps',rsvps) order by day),'[]'::jsonb) from daily),
    'sources',(select coalesce(jsonb_agg(jsonb_build_object('name',source,'total',total) order by total desc,source),'[]'::jsonb) from src)
  ) into result from totals t;
  return result;
end;
$$;

revoke all on function public.analytics_summary(uuid,date,date) from public;
grant execute on function public.analytics_summary(uuid,date,date) to authenticated;

comment on table public.analytics_events is 'Anonymous event analytics for published wedding invitations.';
