-- ============================================================
-- FASE 4 (Tahap 2) — Analitik Kunjungan & Masa Aktif Otomatis
-- Jalankan SETELAH schema.sql, schema_phase2.sql, schema_phase3.sql,
-- schema_phase3b.sql, schema_phase4.sql.
-- Aman dijalankan berkali-kali (idempotent).
-- ============================================================

-- 1) SITE_VIEWS : catat setiap kunjungan halaman undangan (analitik).
create table if not exists public.site_views (
  id         bigint generated by default as identity primary key,
  site_id    uuid references public.sites(id) on delete cascade,
  slug       text,
  path       text,
  referrer   text,
  ua         text,
  created_at timestamptz not null default now()
);
create index if not exists site_views_site_idx on public.site_views (site_id);
create index if not exists site_views_time_idx on public.site_views (created_at);

alter table public.site_views enable row level security;

-- Pengunjung anonim boleh MENCATAT kunjungan (INSERT), tapi tidak boleh membaca.
drop policy if exists site_views_public_insert on public.site_views;
create policy site_views_public_insert on public.site_views
  for insert with check (true);

-- Hanya pemilik undangan atau admin yang boleh MEMBACA data kunjungan.
drop policy if exists site_views_read on public.site_views;
create policy site_views_read on public.site_views
  for select using (
    public.is_admin()
    or exists (select 1 from public.sites s
               where s.id = site_views.site_id and s.owner_id = auth.uid())
  );

-- 2) MASA AKTIF : kolom penanda "sudah dikirimi pengingat perpanjangan".
alter table public.sites add column if not exists expiry_reminded_at timestamptz;

-- 3) RPC ANALITIK : ringkasan untuk panel admin (dijaga -> hanya admin).
--    Mengembalikan JSON: total kunjungan, kunjungan dalam N hari, total
--    RSVP & ucapan, rincian per undangan, dan tren harian.
create or replace function public.analytics_overview(days int default 30)
returns json language plpgsql stable security definer set search_path = public as $$
declare result json;
begin
  if not public.is_admin() then
    raise exception 'not authorized';
  end if;
  select json_build_object(
    'total_views',  (select count(*) from public.site_views),
    'views_window', (select count(*) from public.site_views
                      where created_at >= now() - make_interval(days => days)),
    'rsvp_total',   (select count(*) from public.rsvp),
    'wish_total',   (select count(*) from public.wishes),
    'per_site', (
      select coalesce(json_agg(x), '[]'::json) from (
        select v.site_id,
               s.slug,
               count(*)            as views,
               max(v.created_at)   as last_view,
               (select count(*) from public.rsvp r where r.site_id = v.site_id)   as rsvp,
               (select count(*) from public.wishes w where w.site_id = v.site_id) as wishes
        from public.site_views v
        left join public.sites s on s.id = v.site_id
        group by v.site_id, s.slug
        order by views desc
        limit 100
      ) x
    ),
    'daily', (
      select coalesce(json_agg(d), '[]'::json) from (
        select to_char(date_trunc('day', created_at), 'YYYY-MM-DD') as day,
               count(*) as views
        from public.site_views
        where created_at >= now() - make_interval(days => days)
        group by 1 order by 1
      ) d
    )
  ) into result;
  return result;
end; $$;

-- Cabut akses default; hanya lewat RLS/guard is_admin() di dalam fungsi.
revoke all on function public.analytics_overview(int) from public;
grant execute on function public.analytics_overview(int) to anon, authenticated;

-- ============================================================
-- SELESAI.
--  • Pelacakan kunjungan otomatis dikirim oleh db.js (INSERT ke site_views).
--  • Auto-expire + pengingat perpanjangan dijalankan fungsi terjadwal
--    netlify/functions/expiry-cron.js (schedule "@daily" di netlify.toml).
-- ============================================================
