/* Wedding Studio Priority 11 — performance, fallbacks and accessibility. */
(function(){
'use strict';if(window.WEDDING_PERFORMANCE)return;
var root=document.documentElement,forcedLite=false,processed=new WeakSet(),mapTimers=new WeakMap();
var mq=window.matchMedia?matchMedia('(prefers-reduced-motion: reduce)'):{matches:false,addEventListener:function(){}};
function connection(){var c=navigator.connection||navigator.mozConnection||navigator.webkitConnection||{};return{effectiveType:c.effectiveType||'unknown',saveData:!!c.saveData,downlink:Number(c.downlink||0),rtt:Number(c.rtt||0)};}
function weak(){var c=connection();return forcedLite||c.saveData||/^(slow-)?2g$/.test(c.effectiveType)||(navigator.deviceMemory&&navigator.deviceMemory<=2)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=2);}
function applyMode(){root.classList.toggle('p11-reduced',!!mq.matches);root.classList.toggle('p11-lite',weak());root.dataset.performanceMode=weak()?'lite':'full';}
var css=':focus-visible{outline:3px solid #c99b43!important;outline-offset:3px!important}button,.btn,.map-btn,.t5-route,.copy-btn,#musicBtn,.music-btn{min-height:44px;min-width:44px}img.p11-pending{background:linear-gradient(100deg,#eee8dc 20%,#faf7f0 40%,#eee8dc 60%);background-size:220% 100%;animation:p11Shimmer 1.4s ease infinite}img.p11-loaded{background:none}img.p11-failed{object-fit:contain!important;background:#f4efe5!important}.p11-map-fallback{display:none!important;align-items:center;justify-content:center;gap:6px;margin:8px auto 0;min-height:44px;padding:8px 13px;border:1px solid currentColor;border-radius:999px;text-decoration:none}.p11-map-failed+.p11-map-fallback,.p11-map-fallback.is-visible{display:inline-flex!important}.p11-media-error{opacity:.7!important;cursor:not-allowed!important}@keyframes p11Shimmer{to{background-position:-220% 0}}@media(prefers-contrast:more){body{color:#111!important}.btn,.map-btn,.copy-btn,.t5-route{border:2px solid currentColor!important;text-shadow:none!important}}html.p11-reduced *,html.p11-reduced *:before,html.p11-reduced *:after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-delay:0ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}html.p11-lite .petal,html.p11-lite .falling,html.p11-lite .particle,html.p11-lite [class*=confetti],html.p11-lite [class*=sparkle],html.p11-lite [class*=ornament-float]{display:none!important}html.p11-lite *,html.p11-lite *:before,html.p11-lite *:after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.12s!important}';
var style=document.createElement('style');style.id='p11-runtime-style';style.textContent=css;(document.head||document.documentElement).appendChild(style);
function fallbackSvg(){var s='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><rect width="1200" height="800" fill="#f3ede2"/><circle cx="600" cy="330" r="84" fill="#d8c7a7"/><path d="M380 650l155-170 105 110 90-90 130 150" fill="none" stroke="#b79b6b" stroke-width="24" stroke-linecap="round" stroke-linejoin="round"/><text x="600" y="730" text-anchor="middle" font-family="Arial,sans-serif" font-size="34" fill="#78684f">Foto belum tersedia</text></svg>';return'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s);}
function isHero(img){return!!img.closest('#hero,#cover,.hero,.cover,.opening,.p2-photo-host');}
function image(img){if(!img||processed.has(img))return;processed.add(img);var hero=isHero(img);img.decoding='async';if(hero){img.loading='eager';try{img.fetchPriority='high'}catch(e){}}else{img.loading='lazy';try{img.fetchPriority='low'}catch(e){}}if(!img.hasAttribute('alt'))img.alt=img.getAttribute('data-alt')||(hero?'Foto sampul pernikahan':'Foto pernikahan');img.classList.add('p11-pending');function loaded(){img.classList.remove('p11-pending');img.classList.add('p11-loaded')}function failed(){if(img.dataset.p11Fallback)return;img.dataset.p11Fallback='1';img.dataset.p11Original=img.currentSrc||img.src||'';img.removeAttribute('srcset');img.src=fallbackSvg();img.alt=img.alt||'Foto tidak tersedia';img.classList.remove('p11-pending');img.classList.add('p11-failed');document.dispatchEvent(new CustomEvent('wedding:media-fallback',{detail:{type:'image'}}))}img.addEventListener('load',loaded,{once:true});img.addEventListener('error',failed,{once:true});if(img.complete){if(img.naturalWidth)loaded();else if(img.src)failed();}}
function mapFrame(frame){if(!frame||frame.dataset.p11Map)return;var key=(frame.src||'')+' '+(frame.title||'');if(!/maps?|peta/i.test(key))return;frame.dataset.p11Map='1';frame.loading='lazy';var link=document.createElement('a'),route=frame.parentElement&&frame.parentElement.querySelector('.t5-route,.map-btn,a[href*=maps]');link.className='p11-map-fallback';link.target='_blank';link.rel='noopener';link.textContent='📍 Buka lokasi di Google Maps';link.href=route&&route.href||frame.src||'#';frame.insertAdjacentElement('afterend',link);var done=false;frame.addEventListener('load',function(){done=true;clearTimeout(mapTimers.get(frame))},{once:true});frame.addEventListener('error',function(){frame.classList.add('p11-map-failed');link.classList.add('is-visible')},{once:true});mapTimers.set(frame,setTimeout(function(){if(!done){frame.classList.add('p11-map-failed');link.classList.add('is-visible')}},10000));}
function media(){document.querySelectorAll('audio').forEach(function(a){if(a.dataset.p11Audio)return;a.dataset.p11Audio='1';a.preload='metadata';a.addEventListener('error',function(){var b=document.querySelector('#musicBtn,.music-btn');if(b){b.classList.add('p11-media-error');b.setAttribute('aria-label','Musik tidak tersedia');b.title='Musik tidak dapat dimuat'}},{once:true})});var b=document.querySelector('#musicBtn,.music-btn');if(b){if(!b.getAttribute('aria-label'))b.setAttribute('aria-label','Putar atau hentikan musik');if(!b.getAttribute('title'))b.title='Kontrol musik';if(b.tagName!=='BUTTON'&&!b.hasAttribute('tabindex'))b.tabIndex=0;}}
function scan(node){var base=node&&node.querySelectorAll?node:document;if(base.matches&&base.matches('img'))image(base);if(base.matches&&base.matches('iframe'))mapFrame(base);base.querySelectorAll('img').forEach(image);base.querySelectorAll('iframe').forEach(mapFrame);media();}
function visible(el){var r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden';}
function report(){var nav=performance.getEntriesByType&&performance.getEntriesByType('navigation')[0],res=performance.getEntriesByType?performance.getEntriesByType('resource'):[],imgs=[].slice.call(document.images),controls=[].slice.call(document.querySelectorAll('button,a[href],input[type=button],input[type=submit],[role=button]')).filter(visible),small=controls.filter(function(x){var r=x.getBoundingClientRect();return r.width<40||r.height<40}).length,bytes=res.reduce(function(n,x){return n+(x.transferSize||0)},0),hero=imgs.filter(isHero).length,lazy=imgs.filter(function(x){return x.loading==='lazy'}).length,altMissing=imgs.filter(function(x){return!x.hasAttribute('alt')}).length,failed=imgs.filter(function(x){return x.dataset.p11Fallback}).length,webp=imgs.filter(function(x){return /\.webp(?:\?|$)/i.test(x.dataset.p11Original||x.currentSrc||x.src||'')}).length,load=Math.round(nav?nav.loadEventEnd||performance.now():performance.now()),score=100;score-=Math.min(25,altMissing*5);score-=Math.min(20,small*2);score-=Math.min(20,failed*5);if(imgs.length-hero>lazy)score-=15;if(load>4000)score-=10;if(load>7000)score-=10;return{score:Math.max(0,score),loadMs:load,transferBytes:bytes,resourceCount:res.length,imageCount:imgs.length,heroImages:hero,lazyImages:lazy,webpImages:webp,missingAlt:altMissing,failedMedia:failed,mapFallbacks:document.querySelectorAll('.p11-map-fallback').length,touchTargets:controls.length,smallTouchTargets:small,reducedMotion:!!mq.matches,liteMode:weak(),connection:connection(),timestamp:new Date().toISOString()};}
function send(){var r=report();try{parent.postMessage({type:'WEDDING_PERFORMANCE_REPORT',report:r},'*')}catch(e){}document.dispatchEvent(new CustomEvent('wedding:performance-ready',{detail:r}));return r;}
window.WEDDING_PERFORMANCE={version:'1.0.0',getReport:report,setLiteMode:function(v){forcedLite=!!v;applyMode();return send()},rescan:function(){scan(document);return report()}};
window.addEventListener('message',function(e){var d=e.data||{};if(d.type==='WEDDING_PERFORMANCE_AUDIT')send();if(d.type==='WEDDING_PERFORMANCE_LITE'){forcedLite=!!d.enabled;applyMode();send()}});
applyMode();if(mq.addEventListener)mq.addEventListener('change',applyMode);else if(mq.addListener)mq.addListener(applyMode);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){scan(document)});else scan(document);
new MutationObserver(function(ms){ms.forEach(function(m){[].slice.call(m.addedNodes).forEach(function(n){if(n.nodeType===1){if(n.matches&&n.matches('img'))image(n);scan(n)}})})}).observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('load',function(){scan(document);setTimeout(send,50)},{once:true});
})();
