#!/usr/bin/env node
'use strict';
const assert=require('assert'),crypto=require('crypto'),path=require('path');
const root=path.resolve(__dirname,'..'),uid='11111111-1111-4111-8111-111111111111',other='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',site='22222222-2222-4222-8222-222222222222',order='33333333-3333-4333-8333-333333333333';let count=0;
function response(ok,data,status){return{ok,status:status||(ok?200:400),json:async()=>data,text:async()=>JSON.stringify(data)}}
function fresh(file){const p=path.join(root,file);delete require.cache[require.resolve(p)];return require(p)}
function event(method,body,token='token'){return{httpMethod:method,headers:{origin:'https://example.test',authorization:token?'Bearer '+token:''},body:JSON.stringify(body||{}),queryStringParameters:body||{}}}
function check(name,fn){return Promise.resolve().then(fn).then(()=>{count++;console.log('✓',name)})}
function env(){Object.assign(process.env,{SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'service'+'-key',PUBLIC_BASE_URL:'https://example.test',PAYMENT_PROVIDER:'midtrans',MIDTRANS_SERVER_KEY:'server'+'-key',MIDTRANS_IS_PRODUCTION:'false',XENDIT_CALLBACK_TOKEN:'callback-token'})}
async function createHandler(options={}){env();let provider=0,inserted=null;global.fetch=async(url,opt={})=>{const u=String(url),method=opt.method||'GET';if(u.includes('/auth/v1/user'))return options.noUser?response(false,{},401):response(true,{id:options.user||uid,email:'test@example.com'});if(u.includes('/rest/v1/plans?'))return response(true,[{id:'premium',name:'Premium',price:199000,duration_months:12,features:{gallery:12}}]);if(u.includes('/rest/v1/sites?'))return response(true,options.noSite?[]:[{id:site,owner_id:uid,status:'draft'}]);if(u.includes('/rest/v1/orders?')&&method==='GET'){if(u.includes('status=eq.pending')&&options.reuse)return response(true,[{id:order,payment_url:'https://sandbox.test/resume',amount:199000,currency:'IDR',expires_at:new Date(Date.now()+3600000).toISOString(),provider:'midtrans'}]);return response(true,[])}if(u.endsWith('/rest/v1/orders')&&method==='POST'){inserted=JSON.parse(opt.body);return response(true,[{id:order,...inserted}])}if(u.includes('/rest/v1/security_audit_logs'))return response(true,{});if(u.includes('/rest/v1/orders?')&&method==='PATCH')return response(true,[{id:order}]);if(u.includes('/snap/v1/transactions')){provider++;const b=JSON.parse(opt.body);assert.equal(b.transaction_details.gross_amount,199000);return response(true,{redirect_url:'https://sandbox.test/pay'})}throw Error('Unmocked create URL '+u)};return{handler:fresh('netlify/functions/create-payment.js').handler,get provider(){return provider},get inserted(){return inserted}}}
function midPayload(status='settlement',amount='199000.00'){const code='200',p={order_id:order,status_code:code,gross_amount:amount,transaction_status:status};p.signature_key=crypto.createHash('sha512').update(order+code+amount+'server-key').digest('hex');return p}
async function webhook(state,payload,provider='midtrans',headers={}){env();process.env.PAYMENT_PROVIDER=provider;let patch=null,events=0;global.fetch=async(url,opt={})=>{const u=String(url),method=opt.method||'GET';if(u.includes('/rest/v1/orders?')&&method==='GET')return response(true,[{id:order,owner_id:uid,site_id:site,status:state,provider,amount:199000,currency:'IDR',provider_ref:order}]);if(u.includes('/rest/v1/orders?')&&method==='PATCH'){patch=JSON.parse(opt.body);return response(true,[{id:order,status:patch.status}])}if(u.endsWith('/rest/v1/payment_events')){events++;return response(true,{})}throw Error('Unmocked webhook URL '+u)};const h=fresh('netlify/functions/payment-webhook.js').handler;const out=await h({httpMethod:'POST',headers,body:JSON.stringify(payload)});return{out,json:JSON.parse(out.body),patch,events}}
(async()=>{
 await check('Unauthenticated order creation is rejected',async()=>{const x=await createHandler({noUser:true}),r=await x.handler(event('POST',{site_id:site,package:'premium'},''));assert.equal(r.statusCode,401);assert.equal(x.provider,0)});
 await check('Cross-account or unknown site is rejected',async()=>{const x=await createHandler({user:other,noSite:true}),r=await x.handler(event('POST',{site_id:site,package:'premium'}));assert.equal(r.statusCode,403);assert.equal(x.provider,0)});
 await check('Browser price manipulation is ignored',async()=>{const x=await createHandler(),r=await x.handler(event('POST',{site_id:site,package:'premium',amount:1,price:1})),j=JSON.parse(r.body);assert.equal(r.statusCode,200);assert.equal(j.amount,199000);assert.equal(x.inserted.amount,199000);assert.equal(x.provider,1)});
 await check('Existing pending order is resumed',async()=>{const x=await createHandler({reuse:true}),r=await x.handler(event('POST',{site_id:site,package:'premium'})),j=JSON.parse(r.body);assert.equal(r.statusCode,200);assert.equal(j.resumed,true);assert.equal(x.provider,0)});
 await check('Invalid Midtrans signature is rejected',async()=>{const p=midPayload();p.signature_key='bad';const x=await webhook('pending',p);assert.equal(x.out.statusCode,401);assert.equal(x.patch,null)});
 await check('Paid webhook with wrong amount is rejected',async()=>{const x=await webhook('pending',midPayload('settlement','1.00'));assert.equal(x.out.statusCode,409);assert.equal(x.patch,null)});
 await check('Valid settlement activates paid transition',async()=>{const x=await webhook('pending',midPayload());assert.equal(x.out.statusCode,200);assert.equal(x.patch.status,'paid');assert.equal(x.events,1)});
 await check('Duplicate paid webhook is idempotent',async()=>{const x=await webhook('paid',midPayload());assert.equal(x.out.statusCode,200);assert.equal(x.json.idempotent,true);assert.equal(x.patch,null)});
 await check('Out-of-order paid to expired transition is ignored',async()=>{const x=await webhook('paid',midPayload('expire'));assert.equal(x.out.statusCode,200);assert.equal(x.json.ignored,true);assert.equal(x.patch,null)});
 await check('Pending invoice can become expired',async()=>{const x=await webhook('pending',midPayload('expire'));assert.equal(x.out.statusCode,200);assert.equal(x.patch.status,'expired')});
 await check('Paid transaction can become refunded',async()=>{const x=await webhook('paid',midPayload('refund'));assert.equal(x.out.statusCode,200);assert.equal(x.patch.status,'refunded')});
 await check('Xendit callback token is required',async()=>{const x=await webhook('pending',{external_id:order,status:'PAID',paid_amount:199000},'xendit',{'x-callback-token':'wrong'});assert.equal(x.out.statusCode,401);assert.equal(x.patch,null)});
 await check('Payment status blocks cross-account access',async()=>{env();global.fetch=async(url)=>String(url).includes('/auth/v1/user')?response(true,{id:other,email:'other@example.com'}):response(true,[]);const h=fresh('netlify/functions/payment-status.js').handler,r=await h({httpMethod:'GET',headers:{origin:'https://example.test',authorization:'Bearer token'},queryStringParameters:{site_id:site}});assert.equal(r.statusCode,403)});
 console.log(`\nPhase 4 payment/security tests: ${count} passed, 0 failed.`);
})().catch(e=>{console.error('✗',e.stack||e);process.exit(1)});
